platform:
  master:
    serverIp: 127.0.0.1
    serverPort: 8443
    rootPassword: 123456

datasource:
  platform:
    username: root
    password: 123456
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false&useOldAliasMetadataBehavior=false&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    maxPoolSize: 50
    minPoolSize: 10