platform:
  master:
    serverIp: 192.168.18.185
    serverAdminPort: 8443
    serverUserPort: 443
    rootPassword: 123456

datasource:
  platform:
    username: rot
    password: 123456
    jdbcUrl: jdbc:mysql://192.168.18.185:3306/cipher_platform_metadata?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false&useOldAliasMetadataBehavior=false&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    maxPoolSize: 300
    minPoolSize: 10
  dbEncDec:
    proxy:
      mysql:
        jdbcUrl: jdbc:mysql://192.168.18.22:5000/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false&useOldAliasMetadataBehavior=false&allowPublicKeyRetrieval=true
        driverClassName: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        maxPoolSize: 40
        minPoolSize: 3
      mariadb:
        jdbcUrl: jdbc:mariadb://192.168.18.22:5000/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false&useOldAliasMetadataBehavior=false
        driverClassName: org.mariadb.jdbc.Driver
        username: root
        password: 123456
        maxPoolSize: 40
        minPoolSize: 3
      openGauss:
        jdbcUrl: jdbc:opengauss://192.168.18.22:5000/postgres
        driverClassName: org.opengauss.Driver
        username: root
        password: 123456
        maxPoolSize: 100
        minPoolSize: 3
      postgresql:
        jdbcUrl: jdbc:postgresql://127.0.0.1:5000/test?currentSchema=test
        driverClassName: org.postgresql.Driver
        username: root
        password: 123456
        maxPoolSize: 100
        minPoolSize: 3
      sqlserver:
        jdbcUrl: jdbc:sqlserver://127.0.0.1:5000;DatabaseName=test;schemaName=test
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        username: root
        password: 123456
        maxPoolSize: 100
        minPoolSize: 3
      oracle:
        jdbcUrl: jdbc:oracle:thin:@127.0.0.1:5000:test
        driverClassName: oracle.jdbc.OracleDriver
        username: root
        password: 123456
        maxPoolSize: 100
        minPoolSize: 3
      oceanbase:
        jdbcUrl: jdbc:oceanbase://192.168.18.22:5000/test?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&createDatabaseIfNotExist=true
        driverClassName: com.oceanbase.jdbc.Driver
        username: root
        password: 123456
        maxPoolSize: 100
        minPoolSize: 3
    jdbc:
      mysql:
        jdbcUrl: jdbc:dbte:mysql://192.168.17.41:3306/test?dbteConfig=E:/java/workspace/db-enc-dec-autotest/src/main/resources&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false&useOldAliasMetadataBehavior=false&allowPublicKeyRetrieval=true
        #jdbcUrl: jdbc:dbte:mysql://192.168.18.222:3306/test?dbteConfig=E:/java/workspace/db-enc-dec-autotest/src/main/resources&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false&useOldAliasMetadataBehavior=false&allowPublicKeyRetrieval=true
        driverClassName: com.olym.dbte.driver.DbteJdbcDriver
        username: admin
        password: 123456
        maxPoolSize: 40
        minPoolSize: 3
      mariadb:
        jdbcUrl: jdbc:dbte:mariadb://192.168.18.222:3306/test?dbteConfig=E:/java/workspace/db-enc-dec-autotest/src/main/resources&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false&useOldAliasMetadataBehavior=false&allowPublicKeyRetrieval=true
        #jdbcUrl: jdbc:dbte:mariadb://192.168.18.222:3306/test?dbteConfig=E:/java/workspace/db-enc-dec-autotest/src/main/resources&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false&useOldAliasMetadataBehavior=false&allowPublicKeyRetrieval=true
        driverClassName: com.olym.dbte.driver.DbteJdbcDriver
        username: root
        password: 123456
        maxPoolSize: 40
        minPoolSize: 3
      openGauss:
        jdbcUrl: jdbc:dbte:opengauss://192.168.18.22:15432/postgres
        driverClassName: com.olym.dbte.driver.DbteJdbcDriver
        username: gaussdb
        password: 123456
        maxPoolSize: 100
        minPoolSize: 3
      postgresql:
        jdbcUrl: jdbc:dbte:postgresql://192.168.18.41:15040/test?currentSchema=test
        driverClassName: com.olym.dbte.driver.DbteJdbcDriver
        username: sonar
        password: 123456
        maxPoolSize: 100
        minPoolSize: 3
      sqlserver:
        jdbcUrl: jdbc:dbte:sqlserver://127.0.0.1:2433;DatabaseName=test;schemaName=test
        driverClassName: com.olym.dbte.driver.DbteJdbcDriver
        username: root
        password: 123456
        maxPoolSize: 100
        minPoolSize: 3
      oracle:
        #jdbcUrl: jdbc:oracle:thin:@127.0.0.1:1521:test?dbteConfig=E:/java/workspace/db-enc-dec-autotest/src/main/resources
        #jdbcUrl: jdbc:oracle:thin:@192.168.18.11:1521:helowin?dbteConfig=E:/java/workspace/db-enc-dec-autotest/src/main/resources
        jdbcUrl: jdbc:oracle:thin:@192.168.18.222:1521:helowin?dbteConfig=E:/java/workspace/db-enc-dec-autotest/src/main/resources
        driverClassName: com.olym.dbte.driver.DbteJdbcDriver
        username: test
        password: test
        maxPoolSize: 100
        minPoolSize: 3
      oceanbase:
        jdbcUrl: jdbc:oceanbase://192.168.18.222:2881/test?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&createDatabaseIfNotExist=true
        driverClassName: com.olym.dbte.driver.DbteJdbcDriver
        username: root
        password: 123456
        maxPoolSize: 100
        minPoolSize: 3
    direct:
      mysql:
        jdbcUrl: jdbc:mysql://192.168.17.41:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false&useOldAliasMetadataBehavior=false&allowPublicKeyRetrieval=true
        #jdbcUrl: jdbc:mysql://192.168.18.222:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false&useOldAliasMetadataBehavior=false&allowPublicKeyRetrieval=true
        driverClassName: com.mysql.cj.jdbc.Driver
        username: admin
        password: 123456
        maxPoolSize: 40
        minPoolSize: 3
      mariadb:
        jdbcUrl: jdbc:mariadb://192.168.18.222:49154/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false&useOldAliasMetadataBehavior=false
        driverClassName: org.mariadb.jdbc.Driver
        username: root
        password: 123456
        maxPoolSize: 40
        minPoolSize: 3
      openGauss:
        jdbcUrl: jdbc:opengauss://192.168.18.22:15432/postgres
        driverClassName: org.opengauss.Driver
        username: gaussdb
        password: 123456
        maxPoolSize: 100
        minPoolSize: 3
      postgresql:
        jdbcUrl: jdbc:postgresql://192.168.18.41:15040/test?currentSchema=test
        driverClassName: org.postgresql.Driver
        username: sonar
        password: 123456
        maxPoolSize: 100
        minPoolSize: 3
      sqlserver:
        jdbcUrl: jdbc:sqlserver://127.0.0.1:2433;DatabaseName=test;schemaName=test
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        username: root
        password: 123456
        maxPoolSize: 100
        minPoolSize: 3
      oracle:
        jdbcUrl: jdbc:oracle:thin:@192.168.18.222:1521:helowin
        #jdbcUrl: jdbc:oracle:thin:@192.168.18.11:1521:helowin
        #jdbcUrl: jdbc:oracle:thin:@127.0.0.1:1521:test
        driverClassName: oracle.jdbc.OracleDriver
        username: test
        password: test
        maxPoolSize: 100
        minPoolSize: 3
      oceanbase:
        jdbcUrl: jdbc:oceanbase://192.168.18.222:2881/test?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&createDatabaseIfNotExist=true
        driverClassName: com.oceanbase.jdbc.Driver
        username: root
        password: 123456
        maxPoolSize: 100
        minPoolSize: 3